### ISSUE TITLE
Re: Unable to compile on windows

### ISSUE THREAD

**Issue by numToStr** [vorot93/libmdbx-rs#1]
Originally posted here https://github.com/Kerollmops/heed/issues/107

Currently, https://github.com/Kerollmops/heed with `mdbx` backend is not compiling on windows. Also, @erthink pointed out that the issue might be in the bindings.

I am still new to rust but I am willing to help ✌🏻

**Comment by erthink** [comment]
@numToStr, You might want to ask @vorot93 about the availability/readiness of another libmdbx-to-Rust binding that (AFAIK) is being developed for [Erigon](https://github.com/ledgerwatch/erigon) project.

**Comment by numToStr** [comment]
@erthink I think, I found it https://github.com/vorot93/mdbx-rs

Edit: but sadly it is not yet published.

**Comment by Kerollmops** [comment]
I am open to pull requests, as I am not really using mdbx-rs for my own project, I could also give the ownership to anyone who want it.

**Comment by erthink** [comment]
@vorot93, I suggest you think about taking this project to yourself.
This seems reasonable if you expect me to solve https://github.com/erthink/libmdbx/issues/200 and https://github.com/erthink/libmdbx/issues/203.

**Comment by vorot93** [comment]
@Kerollmops could you please transfer this repo to `rust-ethereum` then and give me the rights to publish `mdbx-sys` to crates.io?

**Comment by Kerollmops** [comment]
I can't transfer it to the `rust-ethereum` organization directly, I don't have the right to create a public repository. I can transfer it to you if you have the right to create public repositories in the `rust-ethereum` organization, this way you can transfer it by yourself.

On the other hand, I sent you an invite to publish new releases of `mdbx-sys` on crates.io.

**Comment by vorot93** [comment]
@Kerollmops yep, that would work too

**Comment by sauliusgrigaitis** [comment]
Great work on `mdbx-rs`!

We consider replacing RocksDB with MDBX in Grandine. One of the criteria is the support of the all three Linux, macOS and Windows. Could you let me know when Windows support is planned? Or this is a very low priority?

**Comment by vorot93** [comment]
@sauliusgrigaitis Windows _is_ a low-priority target to me. Given that, the error looks trivial to fix, so let's see what can be done.

**Comment by iquiw** [comment]
I could build an app that depends on `mdbx-sys` through `heed` on Windows by using the build script.

```rust
fn main() {
    println!("cargo:rustc-link-lib=dylib=ntdll");
    println!("cargo:rustc-link-lib=dylib=user32");
}
```

**Comment by vorot93** [comment]
Should work on Windows now
