### ISSUE TITLE
Windows builds failing

### ISSUE THREAD

**Issue by simc** [vorot93/libmdbx-rs#10]
For windows builds (locally and on the CI) I always get the following error:
```
LINK : warning LNK4098: defaultlib 'MSVCRTD' conflicts with use of other libs; use /NODEFAULTLIB:library
          mdbx.lib(mdbx.c.obj) : error LNK2019: unresolved external symbol __imp_CharToOemBuffA referenced in function mdbx_strerror_r_ANSI2OEM
```

Any ideas what could be wrong?

**Comment by erthink** [comment]
Hmm, I haven't seen any logs. However, it is quite obvious that in your case, for some reason, the list of linked libraries is incorrect:
 - contains more than one MSVC CRT libraries, for instance the `MSVCRTD` and same for another debug/threading/dll case.
 - don't include `user32` which is required for `CharToOemBuffA()`.

**Comment by erthink** [comment]
Please try the [`rust-issue-10-windows`](https://github.com/erthink/libmdbx/tree/rust-issue-10-windows) branch.
