### ISSUE TITLE
Cannot set page_size

### ISSUE THREAD

**Issue by adriantombu** [vorot93/libmdbx-rs#11]
Hello, and thanks for this crate!

I'm trying to set the `page_size` Geometry attribute in the `set_geometry` function but it looks like it's only possible to do so with `PageSize::Set()` to get the proper `PageSize` type for this value and it is located in a private module, so I can't access it.

So if I try `libmdbx::environment::PageSize::Set(...)` then I have the `module 'environment' is private` error obviously.

Thanks in advance for your insight! I'm pretty new to Rust so sorry in advance if I missed something obvious 👀

**Comment by vorot93** [comment]
Implemented in master
