### ISSUE TITLE
`map_resize` assertion failure

### ISSUE THREAD

**Issue by jeromegn** [vorot93/libmdbx-rs#16]
I'm seeing these in my logs:

```
mdbx:9268: map_resize: Assertion `size_bytes == env->me_dxb_mmap.current' failed.
```

This is how I've setup libmdbx:

```rust
const GIB: usize = 1024 * 1024 * 1024;
const MIN_DB_SIZE: usize = GIB;
const MAX_DB_SIZE: usize = 10 * GIB;

let env = Environment::new()
            .set_max_dbs(1024)
            .set_geometry(libmdbx::Geometry {
                size: Some(MIN_DB_SIZE..MAX_DB_SIZE),
                growth_step: None,
                shrink_threshold: None,
                page_size: None,
            })
            .open(path.as_ref())?;
```

Should I be doing things differently? My DB is using about 2GB on disk right now.

**Comment by hrxi** [comment]
We started hitting this assert with libmdbx 0.1.8. Can you test whether the issue goes away with libmdx 0.1.7? (https://github.com/nimiq/core-rs-albatross/issues/1014)

**Comment by jeromegn** [comment]
Unfortunately we moved off of mdbx due to its durability tradeoffs (my bad for the upfront research, nothing about mdbx)

**Comment by vorot93** [comment]
This really looks like upstream error. Please report on Telegram: https://t.me/libmdbx

**Comment by hrxi** [comment]
Reported on upstream issue tracker: https://gitflic.ru/project/erthink/libmdbx/issue/7.
