### ISSUE TITLE
Update of bitflags to version 2 is backwards-incompatible

### ISSUE THREAD

**Issue by sisou** [vorot93/libmdbx-rs#22]
As noted in the release notes for bitflags v2 (https://github.com/bitflags/bitflags/releases/tag/2.0.0), the library changed in a backward-incompatible way, and you need to add new trait derives to your publicly exposed bitflags.

In our case, we require the `Debug` trait, which is now no longer derived automatically in v2. But it would probably be good to add all the previously derived traits, as shown in the above-linked release notes:

In `src/flags.rs` for both `TableFlags` and `WriteFlags`:
```diff
- #[derive(Default)]
+ #[derive(Default, PartialEq, Eq, PartialOrd, Ord, Hash, Debug, Clone, Copy)]
```

**Comment by vorot93** [comment]
Thanks for the heads up! Should be fixed in master.
